django_ecommerce1/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'products.views.home', name='home'),
    url(r'^s/$', 'products.views.search', name='search'),
    url(r'^products/$', 'products.views.all', name='products'),
    url(r'^products/(?P<slug>[\w-]*)/$', 'products.views.single', name='single_product'),
    url(r'^cart/(?P<id>\d+)/$', 'carts.views.remove_from_cart', name='remove_from_cart'),
    url(r'^cart/(?P<slug>[\w-]*)/$', 'carts.views.add_to_cart', name='add_to_cart'),
    url(r'^cart/$', 'carts.views.view', name='cart'),
    url(r'^checkout/$', 'orders.views.checkout', name='checkout'),
    url(r'^orders/$', 'orders.views.orders', name='user_orders'),
    url(r'^ajax/dismiss_marketing_message/$', 'marketing.views.dismiss_marketing_message', name='dismiss_marketing_message'),
    url(r'^ajax/email_signup/$', 'marketing.views.email_signup', name='ajax_email_signup'),
    url(r'^ajax/add_user_address/$', 'accounts.views.add_user_address', name='ajax_add_user_address'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/logout/$', 'accounts.views.logout_view', name='auth_logout'),
    url(r'^accounts/login/$', 'accounts.views.login_view', name='auth_login'),
    url(r'^accounts/register/$', 'accounts.views.registration_view', name='auth_register'),
    url(r'^accounts/address/add/$', 'accounts.views.add_user_address', name='add_user_address'),
    url(r'^accounts/activate/(?P<activation_key>\w+)/$', 'accounts.views.activation_view', name='activation_view'),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from django.conf import settings

# Create your models here.
from accounts.models import UserAddress
from carts.models import Cart
from decimal import Decimal


STATUS_CHOICES = (
    ('Started', 'Started'),
    ('Abandoned', 'Abandoned'),
    ('Finished', 'Finished'),
)


try:
    tax_rate = settings.DEFAULT_TAX_RATE
except Exception, e:
    raise NotImplementedError(str(e))


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    order_id = models.CharField(max_length=120, default='ABC', unique=True)
    cart = models.ForeignKey(Cart)
    status = models.CharField(max_length=120, choices=STATUS_CHOICES, default='Started')
    # add address
    shipping_address = models.ForeignKey(UserAddress, related_name='shipping_address', blank=True, null=True)
    billing_address = models.ForeignKey(UserAddress, related_name='billing_address', blank=True, null=True)
    sub_total = models.DecimalField(default=Decimal(str(10.99)), max_digits=1000, decimal_places=2) # Python 2.6 do not support Decimal
    tax_total = models.DecimalField(default=Decimal(str(0.99)), max_digits=1000, decimal_places=2)
    final_total = models.DecimalField(default=Decimal(str(10.99)), max_digits=1000, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __unicode__(self):
        return self.order_id

    def get_final_amount(self):
        two_places = Decimal(10)==-2
        tax_rate_dec = Decimal(str(tax_rate))
        self.tax_total = Decimal(tax_rate_dec * self.sub_total).quantize(two_places)
        self.final_total = self.sub_total + self.tax_total
        self.save()
        return self.final_total

orders/views.py
import stripe

from django.shortcuts import render, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
from accounts.models import UserAddress
from accounts.forms import UserAddressForm
from carts.models import Cart
from .models import Order
from .utils import id_generator

try:
    stripe_pub = settings.STRIPE_PUBLISHABLE_KEY
    stripe_secret = settings.STRIPE_SECRET_KEY
except Exception, e:
    raise NotImplementedError(str(e))

stripe.api_key = stripe_secret

def orders(request):
    context = {}
    template = "orders/user.html"
    return render(request, template, context)

# require user login
@login_required
def checkout(request):

    try:
        the_id = request.session['cart_id']
        cart = Cart.objects.get(id=the_id)
    except:
        the_id = None
        return HttpResponseRedirect(reverse("cart"))

    try:
        new_order = Order.objects.get(cart=cart)
    except Order.DoesNotExist:
        new_order = Order()
        new_order.cart = cart
        new_order.user = request.user
        new_order.order_id = id_generator()
        new_order.save()
    except:
        new_order = None
        # work on some error messages
        return HttpResponseRedirect(reverse("cart"))

    final_amount = 0
    if new_order is not None:
        new_order.sub_total = cart.total
        new_order.save()
        final_amount = new_order.get_final_amount()

    address_form = UserAddressForm()
    try:
        address_added = request.GET.get('address_added')
    except:
        address_added = None

    if address_added is None:
       address_form = UserAddressForm()   
    else:
       address_form = None

    current_addresses = UserAddress.objects.filter(user=request.user)
    billing_addresses = UserAddress.objects.get_billing_address(user=request.user)
    # assign an address
    # run credit card

    if request.method == "POST":
        try:
            user_stripe = request.user.userstripe.stripe_id
            customer = stripe.Customer.retrieve(user_stripe)
            print customer
        except:
            customer = None

        if customer is not None:
            shipping_a = request.POST['shipping_address']
            billing_a = request.POST['billing_address']
            token = request.POST['stripeToken']

            try:
                shipping_address_instance = UserAddress.objects.get(id=shipping_a)
            except:
                shipping_address_instance = None
            try:
                billing_address_instance = UserAddress.objects.get(id=billing_a)
            except:
                billing_address_instance = None

            card = customer.sources.create(source=token)
            card.address_city = billing_address_instance.city or None
            card.address_country = billing_address_instance.country or None
            card.address_line1 = billing_address_instance.address or None
            card.address_line2 = billing_address_instance.address2 or None
            card.address_state = billing_address_instance.state or None
            card.address_zip = billing_address_instance.zipcode or None
            card.save()

            charge = stripe.Charge.create(
                amount=int(final_amount * 100),
                currency="usd",
                source=card, # obtained with Stripe.js
                customer=customer,
                description="Charge for %s" % (request.user.username)
            )
            print card
            print charge
            if charge['captured']:
                new_order.status = 'Finished'
                new_order.shipping_address = shipping_address_instance
                new_order.billing_address = billing_address_instance
                new_order.save()
                # cart.delete()
                del request.session['cart_id']
                del request.session['items_total']
                messages.success(request, 'Thank you for your order. Your order has been completed!')
                return HttpResponseRedirect(reverse("user_orders"))

    context = {
        'order': new_order,
        'address_form': address_form,
        'current_addresses': current_addresses,
        'billing_addresses': billing_addresses,
        'stripe_pub': stripe_pub
    }
    template = "orders/checkout.html"
    return render(request, template, context)

templates/orders/checkout.html
{% extends "base.html" %}

{% block head_styles %}
.radio-label {
  font-size: 22px;
  font-weight: normal;
  padding: 4px 30px;
  border-radius: 8px;
  border: 1px solid #ccc;
}

.radio-label input[type=radio] {
  display: none;
}

.radio-label:hover, .radio-label-selected {
  font-size: 22px;
  font-weight: normal;
  background-color: #428bca;
  color: white;
  cursor: pointer;
  padding: 4px 30px;
  border-radius: 8px;
}

.billing-label {
  font-size: 22px;
  font-weight: normal;
  padding: 4px 30px;
  border-radius: 8px;
  border: 1px solid #ccc;
}

.billing-label input[type=radio] {
  display: none;
}

.billing-label:hover, .billing-label-selected {
  font-size: 22px;
  font-weight: normal;
  background-color: #428bca;
  color: white;
  cursor: pointer;
  padding: 4px 30px;
  border-radius: 8px;
}


@media screen and (min-width: 1200px) {
  .total {
    position: fixed;
  }
}

{% endblock %}

{% block jquery %}
// This identifies your website in the createToken call below
Stripe.setPublishableKey('{{ stripe_pub }}');

jQuery(function($) {
  $('#payment-form').submit(function(event) {
    var $form = $(this);

    // Disable the submit button to prevent repeated clicks
    $form.find('button').prop('disabled', true);

    Stripe.card.createToken($form, stripeResponseHandler);

    // Prevent the form from submitting with the default action
    return false;
  });
});

function stripeResponseHandler(status, response) {
  var $form = $('#payment-form');

  if (response.error) {
    // Show the errors on the form
    $('#card_errors_div').removeClass('hidden');
    $form.find('.payment-errors').text(response.error.message);
    $form.find('button').prop('disabled', false);
  } else {
    // response contains id and card, which contains additional card details
    var token = response.id;
    // Insert the token into the form so it gets submitted to the server
    $('#card_errors_div').addClass('hidden');
    $form.append($('<input type="hidden" name="stripeToken" />').val(token));
    // and submit
    $form.get(0).submit();
  }
};


$(".radio-label").click(function(){
  $("label").removeClass("radio-label-selected");
  $(this).addClass("radio-label-selected");
})

$(".billing-label").click(function(){
  $("label").removeClass("billing-label-selected");
  $(this).addClass("billing-label-selected");
})

$("#addShippingAddress").click(function(e){
  e.preventDefault();
  $("#shippingAddressForm").fadeToggle();
})

{% if not current_addresses %}
$("#shippingAddressForm").fadeToggle();
{% endif %}

{% endblock %}


{% block content %}

<div class="col-sm-3 pull-right">
  <div class="total">
    <h1>Current total: {{ order.get_final_amount }}</h1>
    <a href="#">Finalize Checkout</a>
  </div>
</div>


<div class="col-sm-9 pull-left">

  <div class="col-sm-12" id="shippingAddressForm" style="display:none;">
    <h3>Add new Shipping Address</h3>
    <form method="POST" action="{% url 'ajax_add_user_address' %}?next=checkout">{% csrf_token %}
  
    {{ address_form.as_p }}
  
      <input type="submit" class="btn btn-default" value="Add Shpping Address" />
    </form>
  </div>
  
  <form method="POST" action="" id="payment-form">{% csrf_token %}
  
  {% if current_addresses %}
  
    <div class="col-sm-12">
      <h3>Shipping Addresses</h3>
  
    {% for address in current_addresses %}
      {% if request.user.userdefaultaddress.shipping.id == address.id %}
      <label class="radio-label radio-label-selected">
        <input type="radio" name="shipping_address" value="{{ address.id }}" checked="checked">{{ address.get_address }}
      </label>
      {% else %}
      <label class="radio-label">
        <input type="radio" name="shipping_address" value="{{ address.id }}">{{ address.get_address }}
      </label>
      {% endif %}
      <br/>
    {% endfor %}
  
      <a href="{% url 'add_user_address' %}" id="addShippingAddress">Add New Address</a>
  
    </div>
  
  {% endif %}
  
  
  {% if billing_addresses %}
  
    <div class="col-sm-12">
      <h3>Billing Addresses</h3>
  
    {% for address in billing_addresses %}
      {% if request.user.userdefaultaddress.billing.id == address.id %}
      <label class="billing-label billing-label-selected">
        <input type="radio" name="billing_address" value="{{ address.id }}" checked="checked">{{ address.get_address }}
      </label>
      {% else %}
      <label class="billing-label">
        <input type="radio" name="billing_address" value="{{ address.id }}">{{ address.get_address }}
      </label>
      {% endif %}
      <br/>
    {% endfor %}
  
    </div>
  
  {% endif %}
  
    <div class="col-md-12">
      <div class="row">
        <div class="col-xs-5">
          <h3>Credit info</h3>
          <div id="card_errors_div" class="alert alert-danger hidden payment-errors" role="alert">
          </div>
        </div>
      </div>
  
      <div class="form-row">
        <div class="row">
          <div class="col-xs-4" style="padding-right: 0">
            <label>
              <span>Card Number</span>
              <input class="form-control" type="text" size="35" data-stripe="number"/>
            </label>
          </div>
          <div class="col-xs-1">
            <label>
              <span>CVC</span>
              <input class="form-control" type="text" size="4" data-stripe="cvc"/>
            </label>
          </div>
        </div>
      </div>
      <br/>
  
  
      <div class="form-row">
        <b>Expiration (MM/YYYY)</b>
        <div class="row">
          <div class="col-xs-2" style="padding-right: 0">
            <input class="form-control" type="text" size="2" data-stripe="exp-month" placeholder="Month, e.g. 12" />
          </div>
          <div class="col-xs-3">
            <input class="form-control" type="text" size="4" data-stripe="exp-year" placeholder="Year, e.g. 2018" />
          </div>
        </div>
      </div>
      <br/>
  
      <button class="btn btn-default btn-lg" type="submit">Submit Payment</button>
    </div>
  
  </form>

</div>

{% endblock %}

templates/orders/user.html
{% extends "base.html" %}

{% block content %}

{{ user.order_set.all }}

{% endblock %}